name: korean_language_app
description: A Korean language test application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^6.5.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.9
  connectivity_plus: ^5.0.2
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  file_picker: ^10.2.0
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_pdfview: ^1.4.0+1
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^15.2.0
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.5.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  record: ^6.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  shorebird_code_push: ^2.0.4
  url_strategy: ^0.3.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flags/
    - assets/icons/
    # - assets/translations/

  # fonts:
    # - family: Pretendard
    #   fonts:
    #     - asset: assets/fonts/Pretendard-Regular.otf
    #     - asset: assets/fonts/Pretendard-Medium.otf
    #       weight: 500
    #     - asset: assets/fonts/Pretendard-Bold.otf
    #       weight: 700
