name: korean_language_app
description: A Korean language test application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^6.5.0
  cached_network_image: ^3.3.0
  cloud_firestore: ^5.6.6
  connectivity_plus: ^5.0.2
  crypto: ^3.0.6
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  file_picker: ^10.0.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_pdfview: ^1.4.0
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.4
  go_router: ^12.1.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  logger: ^2.0.2+1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0
  pull_to_refresh: ^2.0.0
  record: ^6.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flags/
    - assets/icons/
    # - assets/translations/

  # fonts:
    # - family: Pretendard
    #   fonts:
    #     - asset: assets/fonts/Pretendard-Regular.otf
    #     - asset: assets/fonts/Pretendard-Medium.otf
    #       weight: 500
    #     - asset: assets/fonts/Pretendard-Bold.otf
    #       weight: 700
