import 'package:flutter/material.dart';
import 'package:korean_language_app/shared/enums/book_level.dart';
import 'package:korean_language_app/shared/enums/course_category.dart';
import 'package:korean_language_app/shared/enums/file_upload_type.dart';
import 'package:korean_language_app/features/auth/presentation/bloc/auth_cubit.dart';
import 'package:korean_language_app/features/books/presentation/bloc/korean_books/korean_books_cubit.dart';
import 'package:korean_language_app/features/book_upload/presentation/bloc/file_upload_cubit.dart';
import 'package:korean_language_app/features/books/data/models/book_item.dart';
import 'dart:io';
import 'package:flutter_bloc/flutter_bloc.dart';

class BookUploadPage extends StatefulWidget {
  const BookUploadPage({super.key});

  @override
  State<BookUploadPage> createState() => _BookUploadPageState();
}

class _BookUploadPageState extends State<BookUploadPage> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _durationController = TextEditingController(text: '30 mins');
  final _chaptersController = TextEditingController(text: '1');
  final _countryController = TextEditingController(text: 'Korea');
  final _categoryController = TextEditingController(text: 'Language');
  
  BookLevel _selectedLevel = BookLevel.beginner;
  CourseCategory _selectedCategory = CourseCategory.korean;
  IconData _selectedIcon = Icons.book;
  
  File? _selectedPdfFile;
  String? _pdfFileName;
  bool _pdfSelected = false;
  
  File? _selectedImageFile;
  String? _imageFileName;
  bool _imageSelected = false;

  late KoreanBooksCubit _koreanBooksCubit;
  late FileUploadCubit _fileUploadCubit;
  
  @override
  void initState() {
    super.initState();
    _fileUploadCubit = context.read<FileUploadCubit>();
    _koreanBooksCubit = context.read<KoreanBooksCubit>();
    initialize();
  }
  
  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _durationController.dispose();
    _chaptersController.dispose();
    _countryController.dispose();
    _categoryController.dispose();
    super.dispose();
  }

  initialize() {
    _fileUploadCubit.resetState();
  }
  
  Future<void> _pickPdfFile() async {
    final file = await _fileUploadCubit.pickPdfFile();
    if (file != null) {
      setState(() {
        _selectedPdfFile = file;
        _pdfFileName = file.path.split('/').last;
        _pdfSelected = true;
      });
    }
  }
  
  Future<void> _pickImageFile() async {
    final file = await _fileUploadCubit.pickImageFile();
    if (file != null) {
      setState(() {
        _selectedImageFile = file;
        _imageFileName = file.path.split('/').last;
        _imageSelected = true;
      });
    }
  }
  
  Future<void> _uploadBook() async {
    if (_formKey.currentState?.validate() != true) {
      return;
    }
    
    if (_selectedPdfFile == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a PDF file')),
      );
      return;
    }
    
    try {
      // Get current user from AuthCubit
      final authState = context.read<AuthCubit>().state;
      String? creatorUid;
      
      if (authState is Authenticated) {
        creatorUid = authState.user.uid;
      }
      
      final book = BookItem(
        id: '', // Will be generated by Firebase
        title: _titleController.text,
        description: _descriptionController.text,
        bookImage: null, // Will be updated after upload
        pdfUrl: null, // Will be updated after upload
        duration: _durationController.text,
        chaptersCount: int.tryParse(_chaptersController.text) ?? 1,
        icon: _selectedIcon,
        level: _selectedLevel,
        courseCategory: _selectedCategory,
        country: _countryController.text,
        category: _categoryController.text,
        creatorUid: creatorUid, // Add creator UID
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );
      
      // Upload book with PDF and image atomically
      final success = await _fileUploadCubit.uploadBook(
        book, 
        _selectedPdfFile!, 
        _selectedImageFile
      );
      
      if (success) {
        // Check if we got the uploaded book from the cubit
        final uploadState = _fileUploadCubit.state;
        if (uploadState is FileUploadSuccess && uploadState.book != null) {
          // Add book to KoreanBooksCubit state
          _koreanBooksCubit.addBookToState(uploadState.book!);
        }
        
        _resetForm();
        // ignore: use_build_context_synchronously
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Book uploaded successfully')),
        );
      }
    } catch (e) {
      // ignore: use_build_context_synchronously
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error initiating upload: $e')),
      );
    }
  }
  
  void _resetForm() {
    _titleController.clear();
    _descriptionController.clear();
    _durationController.text = '30 mins';
    _chaptersController.text = '1';
    _countryController.text = 'Korea';
    _categoryController.text = 'Language';
    setState(() {
      _selectedLevel = BookLevel.beginner;
      _selectedCategory = CourseCategory.korean;
      _selectedIcon = Icons.book;
      _selectedPdfFile = null;
      _pdfFileName = null;
      _pdfSelected = false;
      _selectedImageFile = null;
      _imageFileName = null;
      _imageSelected = false;
    });
    _fileUploadCubit.resetState();
  }
  
  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;
    
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Upload New Book',
          style: theme.textTheme.titleLarge?.copyWith(
            fontWeight: FontWeight.bold,
          ),
        ),
        elevation: 0,
        backgroundColor: colorScheme.surface,
      ),
      body: BlocConsumer<FileUploadCubit, FileUploadState>(
        listener: (context, state) {
          if (state is FileUploadSuccess) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Book uploaded successfully')),
            );
            
            // Add book to Korean books state if available
            if (state.book != null) {
              _koreanBooksCubit.addBookToState(state.book!);
            }
            
            _resetForm();
          } else if (state is FileUploadError) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text('Error: ${state.message}')),
            );
          }
        },
        builder: (context, state) {
          bool isUploading = state is FileUploading;
          double uploadProgress = isUploading ? (state).progress : 0.0;
          
          return SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  TextFormField(
                    controller: _titleController,
                    decoration: const InputDecoration(
                      labelText: 'Book Title',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.book),
                    ),
                    enabled: !isUploading,
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter a title';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 16),
                  
                  TextFormField(
                    controller: _descriptionController,
                    decoration: const InputDecoration(
                      labelText: 'Book Description',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.description),
                      alignLabelWithHint: true,
                    ),
                    enabled: !isUploading,
                    maxLines: 4,
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter a description';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 24),
                  
                  Text(
                    'Book Details',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  
                  Row(
                    children: [
                      Expanded(
                        child: TextFormField(
                          controller: _durationController,
                          decoration: const InputDecoration(
                            labelText: 'Duration',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.timer),
                          ),
                          enabled: !isUploading,
                          validator: (value) {
                            if (value == null || value.isEmpty) {
                              return 'Required';
                            }
                            return null;
                          },
                        ),
                      ),
                      const SizedBox(width: 16),
                      
                      Expanded(
                        child: TextFormField(
                          controller: _chaptersController,
                          decoration: const InputDecoration(
                            labelText: 'Chapters',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.format_list_numbered),
                          ),
                          enabled: !isUploading,
                          keyboardType: TextInputType.number,
                          validator: (value) {
                            if (value == null || value.isEmpty) {
                              return 'Required';
                            }
                            if (int.tryParse(value) == null) {
                              return 'Numbers only';
                            }
                            return null;
                          },
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),
                  
                  Row(
                    children: [
                      Expanded(
                        child: TextFormField(
                          controller: _countryController,
                          decoration: const InputDecoration(
                            labelText: 'Country',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.public),
                          ),
                          enabled: !isUploading,
                          validator: (value) {
                            if (value == null || value.isEmpty) {
                              return 'Required';
                            }
                            return null;
                          },
                        ),
                      ),
                      const SizedBox(width: 16),
                      
                      Expanded(
                        child: TextFormField(
                          controller: _categoryController,
                          decoration: const InputDecoration(
                            labelText: 'Category',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.category),
                          ),
                          enabled: !isUploading,
                          validator: (value) {
                            if (value == null || value.isEmpty) {
                              return 'Required';
                            }
                            return null;
                          },
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),
                  
                  Row(
                    children: [
                      Expanded(
                        child: DropdownButtonFormField<BookLevel>(
                          value: _selectedLevel,
                          decoration: const InputDecoration(
                            labelText: 'Level',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.bar_chart),
                          ),
                          items: BookLevel.values.map((level) {
                            return DropdownMenuItem<BookLevel>(
                              value: level,
                              child: Text(level.toString().split('.').last),
                            );
                          }).toList(),
                          onChanged: isUploading 
                              ? null 
                              : (BookLevel? newValue) {
                                  if (newValue != null) {
                                    setState(() {
                                      _selectedLevel = newValue;
                                    });
                                  }
                                },
                        ),
                      ),
                      const SizedBox(width: 16),
                      
                      Expanded(
                        child: DropdownButtonFormField<CourseCategory>(
                          value: _selectedCategory,
                          decoration: const InputDecoration(
                            labelText: 'Course Category',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.school),
                          ),
                          items: CourseCategory.values.map((category) {
                            // Skip favorite as it's not a valid upload category
                            if (category == CourseCategory.favorite) {
                              return null;
                            }
                            return DropdownMenuItem<CourseCategory>(
                              value: category,
                              child: Text(category.toString().split('.').last),
                            );
                          }).where((item) => item != null)
                            .cast<DropdownMenuItem<CourseCategory>>()
                            .toList(),
                          onChanged: isUploading 
                              ? null 
                              : (CourseCategory? newValue) {
                                  if (newValue != null) {
                                    setState(() {
                                      _selectedCategory = newValue;
                                    });
                                  }
                                },
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 24),
                  
                  Text(
                    'Book PDF File (Required)',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  
                  BlocBuilder<FileUploadCubit, FileUploadState>(
                    builder: (context, fileState) {
                      bool isPdfPickerLoading = fileState is FilePickerLoading && 
                                              fileState.fileType == FileUploadType.pdf;
                      
                      return Container(
                        decoration: BoxDecoration(
                          border: Border.all(
                            color: _pdfSelected ? Colors.green : Colors.grey,
                            width: 1,
                          ),
                          borderRadius: BorderRadius.circular(8),
                        ),
                        padding: const EdgeInsets.all(16),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              children: [
                                Icon(
                                  _pdfSelected ? Icons.check_circle : Icons.picture_as_pdf,
                                  color: _pdfSelected ? Colors.green : Colors.grey,
                                ),
                                const SizedBox(width: 8),
                                Expanded(
                                  child: Text(
                                    _pdfFileName ?? 'No PDF selected',
                                    style: TextStyle(
                                      color: _pdfSelected ? Colors.green : Colors.grey,
                                      fontWeight: _pdfSelected ? FontWeight.bold : FontWeight.normal,
                                    ),
                                    maxLines: 1,
                                    overflow: TextOverflow.ellipsis,
                                  ),
                                ),
                              ],
                            ),
                            if (fileState is FilePickerError && fileState.fileType == FileUploadType.pdf)
                              Padding(
                                padding: const EdgeInsets.only(top: 8.0),
                                child: Text(
                                  fileState.message,
                                  style: const TextStyle(color: Colors.red, fontSize: 12),
                                ),
                              ),
                            const SizedBox(height: 16),
                            SizedBox(
                              width: double.infinity,
                              child: ElevatedButton.icon(
                                onPressed: (isUploading || isPdfPickerLoading) ? null : _pickPdfFile,
                                icon: isPdfPickerLoading 
                                    ? const SizedBox(
                                        width: 16, 
                                        height: 16, 
                                        child: CircularProgressIndicator(strokeWidth: 2)
                                      )
                                    : const Icon(Icons.upload_file),
                                label: Text(isPdfPickerLoading ? 'Selecting...' : 'Select PDF File'),
                                style: ElevatedButton.styleFrom(
                                  backgroundColor: colorScheme.primary,
                                  foregroundColor: colorScheme.onPrimary,
                                  padding: const EdgeInsets.symmetric(vertical: 12),
                                ),
                              ),
                            ),
                          ],
                        ),
                      );
                    },
                  ),
                  const SizedBox(height: 24),
                  
                  Text(
                    'Book Cover Image (Optional)',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  
                  BlocBuilder<FileUploadCubit, FileUploadState>(
                    builder: (context, fileState) {
                      bool isImagePickerLoading = fileState is FilePickerLoading && 
                                              fileState.fileType == FileUploadType.image;
                      
                      return Container(
                        decoration: BoxDecoration(
                          border: Border.all(
                            color: _imageSelected ? Colors.green : Colors.grey,
                            width: 1,
                          ),
                          borderRadius: BorderRadius.circular(8),
                        ),
                        padding: const EdgeInsets.all(16),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            if (_selectedImageFile != null)
                              ClipRRect(
                                borderRadius: BorderRadius.circular(8),
                                child: Image.file(
                                  _selectedImageFile!,
                                  height: 150,
                                  width: double.infinity,
                                  fit: BoxFit.cover,
                                ),
                              ),
                            if (_selectedImageFile != null) const SizedBox(height: 16),
                            
                            Row(
                              children: [
                                Icon(
                                  _imageSelected ? Icons.check_circle : Icons.image,
                                  color: _imageSelected ? Colors.green : Colors.grey,
                                ),
                                const SizedBox(width: 8),
                                Expanded(
                                  child: Text(
                                    _imageFileName ?? 'No image selected',
                                    style: TextStyle(
                                      color: _imageSelected ? Colors.green : Colors.grey,
                                      fontWeight: _imageSelected ? FontWeight.bold : FontWeight.normal,
                                    ),
                                    maxLines: 1,
                                    overflow: TextOverflow.ellipsis,
                                  ),
                                ),
                              ],
                            ),
                            if (fileState is FilePickerError && fileState.fileType == FileUploadType.image)
                              Padding(
                                padding: const EdgeInsets.only(top: 8.0),
                                child: Text(
                                  fileState.message,
                                  style: const TextStyle(color: Colors.red, fontSize: 12),
                                ),
                              ),
                            const SizedBox(height: 16),
                            SizedBox(
                              width: double.infinity,
                              child: ElevatedButton.icon(
                                onPressed: (isUploading || isImagePickerLoading) ? null : _pickImageFile,
                                icon: isImagePickerLoading 
                                    ? const SizedBox(
                                        width: 16, 
                                        height: 16, 
                                        child: CircularProgressIndicator(strokeWidth: 2)
                                      )
                                    : const Icon(Icons.upload_file),
                                label: Text(isImagePickerLoading ? 'Selecting...' : 'Select Cover Image'),
                                style: ElevatedButton.styleFrom(
                                  backgroundColor: colorScheme.secondary,
                                  foregroundColor: colorScheme.onSecondary,
                                  padding: const EdgeInsets.symmetric(vertical: 12),
                                ),
                              ),
                            ),
                          ],
                        ),
                      );
                    },
                  ),
                  const SizedBox(height: 32),
                  
                  if (isUploading)
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        LinearProgressIndicator(
                          value: uploadProgress,
                          backgroundColor: Colors.grey[300],
                          valueColor: AlwaysStoppedAnimation<Color>(colorScheme.primary),
                        ),
                        const SizedBox(height: 8),
                        Text(
                          'Uploading ${(uploadProgress * 100).toStringAsFixed(0)}%',
                          style: TextStyle(color: colorScheme.primary),
                        ),
                        const SizedBox(height: 24),
                      ],
                    ),
                  
                  SizedBox(
                    width: double.infinity,
                    height: 50,
                    child: ElevatedButton.icon(
                      onPressed: (isUploading || !_pdfSelected) ? null : _uploadBook,
                      icon: Icon(isUploading ? Icons.hourglass_top : Icons.cloud_upload),
                      label: Text(isUploading ? 'Uploading...' : 'Upload Book'),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: colorScheme.primary,
                        foregroundColor: colorScheme.onPrimary,
                        disabledBackgroundColor: Colors.grey,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}