// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDasav0t4CQMuE95hJHbYw7hlbrI1qzHPQ',
    appId: '1:1016961711599:android:43738c71266a9ed5c0ca1a',
    messagingSenderId: '1016961711599',
    projectId: 'language-test-app-66c35',
    storageBucket: 'language-test-app-66c35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ3tVZ0vlps4cUdA2Bpwy2qFgHM5JUH6A',
    appId: '1:1016961711599:ios:fae04e00b3ce64a9c0ca1a',
    messagingSenderId: '1016961711599',
    projectId: 'language-test-app-66c35',
    storageBucket: 'language-test-app-66c35.firebasestorage.app',
    androidClientId: '1016961711599-mpkud5ivkgth0c5vif8lipa2l2t46ra9.apps.googleusercontent.com',
    iosClientId: '1016961711599-lp4i38dnjcplu6b294phanag63457641.apps.googleusercontent.com',
    iosBundleId: 'com.manasbasnet.koreanlanguageapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpcK7Ca2aggpUbbH4QZ7VVsntXtTYm6-8',
    appId: '1:1016961711599:web:00c33cb21cbdbd10c0ca1a',
    messagingSenderId: '1016961711599',
    projectId: 'language-test-app-66c35',
    authDomain: 'language-test-app-66c35.firebaseapp.com',
    storageBucket: 'language-test-app-66c35.firebasestorage.app',
    measurementId: 'G-LEEGXVYESG',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpcK7Ca2aggpUbbH4QZ7VVsntXtTYm6-8',
    appId: '1:1016961711599:web:f9701f29fdae9e9cc0ca1a',
    messagingSenderId: '1016961711599',
    projectId: 'language-test-app-66c35',
    authDomain: 'language-test-app-66c35.firebaseapp.com',
    storageBucket: 'language-test-app-66c35.firebasestorage.app',
    measurementId: 'G-J05RJJ71P5',
  );

}